module.exports = {
  Logo: require('../Assets/Images/logo.png'),
  Eye: require('../Assets/Icons/eye.png'),
  DropDown: require('../Assets/Icons/dropdown.png'),
  user: require('../Assets/Icons/user.png'),
  play: require('../Assets/Icons/play.png'),
  menu: require('../Assets/Icons/menu.png'),
  search: require('../Assets/Icons/search.png'),
  background: require('../Assets/Images/back.png'),
  home: require('../Assets/Icons/home.png'),
  findPlayer: require('../Assets/Icons/findPlayer.png'),
  messages: require('../Assets/Icons/messages.png'),
  videos: require('../Assets/Icons/videos.png'),
  support: require('../Assets/Icons/support.png'),
  profile: require('../Assets/Icons/profile.png'),
};
