module.exports = {
  Logo: require('../assets/images/logo.png'),
  Eye: require('../assets/icons/eye.png'),
  DropDown: require('../assets/icons/dropdown.png'),
  user: require('../assets/icons/user.png'),
  play: require('../assets/icons/play.png'),
  menu: require('../assets/icons/menu.png'),
  search: require('../assets/icons/search.png'),
  background: require('../assets/images/back.png'),
  home: require('../assets/icons/home.png'),
  findPlayer: require('../assets/icons/findPlayer.png'),
  messages: require('../assets/icons/messages.png'),
  videos: require('../assets/icons/videos.png'),
  support: require('../assets/icons/support.png'),
  profile: require('../assets/icons/profile.png'),
};
